package com.example.chatbot;

import org.springframework.stereotype.Component;

@Component
public class CalendarTranslator {

    public String translate(String title, String lang) {
        return switch (lang) {
            case "zh" -> translateToChinese(title);
            case "en" -> translateToEnglish(title);
            case "vi" -> translateToVietnamese(title);
            default -> title;
        };
    }

    // 中文（沿用你原有顺序）
    private String translateToChinese(String s) {
        return s
                // 本次新增词条（优先长句）
                .replace("1학기 보강기간", "第一学期补课期间")
                .replace("1학기 기말시험", "第一学期期末考试")
                .replace("2학기 개강", "第二学期开学")
                .replace("영진교육재단 설립자 송헌 최달근 박사 추모일", "永进教育财团创始人宋宪、崔达根博士纪念日")
                .replace("2학기 중간시험", "第二学期期中考试")
                .replace("종합작품전(30주) 정상수업", "综合作品展(第30届) 正常上课")
                .replace("2학기 보강기간", "第二学期补课期间")

                // 上一轮已补充词条
                .replace("2026학년도 입학식(50회)", "2026学年第50届入学典礼")
                .replace("수강신청 확인 및 수강정정 기간", "选课申请确认及选课调整期间")
                .replace("수업일수 1/4선", "授课进度1/4")
                .replace("수업일수 3/4선", "授课进度3/4")
                .replace("1학기 중간시험", "第一学期期中考试")
                .replace("백호체육대회", "白虎体育大会")
                .replace("개교기념일(49주년)", "建校纪念日(49周年)")
                .replace("부처님오신날", "佛诞节")
                .replace("대체휴일(부처님오신날)", "佛诞节补休")
                .replace("1학기 개강", "第一学期开学")
                .replace("2학기 기말시험", "第二学期期末考试")

                // 原有通用翻译
                .replace("신정", "元旦")
                .replace("설날연휴", "春节假期")
                .replace("삼일절", "三一节")
                .replace("어린이날", "儿童节")
                .replace("근로자의 날", "劳动节")
                .replace("현충일", "显忠日")
                .replace("광복절", "光复节")
                .replace("개천절", "开天节")
                .replace("한글날", "韩文日")
                .replace("성탄절", "圣诞节")
                .replace("대체휴일", "补休")
                .replace("개강", "开学")
                .replace("하계방학", "暑假")
                .replace("동계방학", "寒假")
                .replace("수강신청", "选课申请")
                .replace("수강정정", "选课调整")
                .replace("보강기간", "补课期间")
                .replace("계절수업", "学期课程")
                .replace("수업일수", "授课日")
                .replace("중간시험", "期中考试")
                .replace("기말시험", "期末考试")
                .replace("신입생 등록 기간", "新生注册期间")
                .replace("재학생 등록", "在校生注册")
                .replace("휴학신청 기간", "休学申请期间")
                .replace("복학신청", "复学申请")
                .replace("입학식", "入学典礼")
                .replace("학위수여식", "学位授予仪式")
                .replace("체육대회", "体育大会")
                .replace("교직원세미나", "教职工研讨会")
                .replace("추모일", "纪念日")
                .replace("개교기념일", "建校纪念日")
                .replace("제9회 지방선거", "第9届地方选举")
                .replace("졸업", "毕业")
                .replace("종합작품전", "综合作品展")
                .replace("선택 확인 및 조정 기간", "选课确认及调整期间")
                .replace("선택 신청 기간", "选课申请期间")
                .replace("백호", "白虎")
                .replace("학교기념일", "建校纪念日")
                .replace("제1학기", "第一学期")
                .replace("제2학기", "第二学期")
                .replace("선택 기간", "选课期间")
                .replace("등록/복학신청", "注册/复学申请")
                .replace("학사일정", "校历")
                .replace("학년도", "学年")
                .replace("회", "届")
                .replace("제", "第")
                .replace("전", "前")
                .replace("후", "后")
                .replace("중간", "中期")
                .replace("기말", "期末")
                .replace("보충", "补充")
                .replace("확인", "确认")
                .replace("기간", "期间")
                .replace("일", "日")
                .replace("개학", "开学")
                .replace("방학", "假期")
                .replace("기", "期")
                .replace("수강", "选课")
                .replace("등록", "注册")
                .replace("휴학", "休学")
                .replace("복학", "复学")
                .replace("졸업식", "毕业典礼")
                .replace("입학", "入学")
                .replace("학위수여", "学位授予")
                .replace("체육", "体育")
                .replace("대회", "大会")
                .replace("교직원", "教职工")
                .replace("세미나", "研讨会")
                .replace("추모", "纪念")
                .replace("개교", "建校")
                .replace("지방선거", "地方选举")
                .replace("선거", "选举")
                .replace("작품전", "作品展")
                .replace("1/4선", "1/4进度")
                .replace("2/4선", "2/4进度")
                .replace("3/4선", "3/4进度")
                .replace("4/4선", "4/4进度")
                .replace("선", "进度")
                .replace("하계", "夏季")
                .replace("동계", "冬季")
                .replace("보강", "补课")
                .replace("수강신청확인및수강정정기간", "选课申请确认及调整期间")
                .replace("수업일수2/4선", "授课进度2/4")
                .replace("수업일수4/4선", "授课进度4/4")
                .replace("2학기개강", "第二学期开学")
                .replace("2학기기말시험", "第二学期期末考试")
                .replace("추석연휴", "中秋假期");
    }

    // 英文（完全对应上面顺序）
    private String translateToEnglish(String s) {
        return s
                // 本次新增词条（优先长句）
                .replace("1학기 보강기간", "1st Semester Makeup Class Period")
                .replace("1학기 기말시험", "1st Semester Final Exam")
                .replace("2학기 기말시험", "2st Semester Final Exam")
                .replace("2학기 개강", "2nd Semester Begins")
                .replace("영진교육재단 설립자 송헌 최달근 박사 추모일", "Memorial Day for Dr. Song Heon & Dr. Choi Dal-geun, Founders of Youngjin Education Foundation")
                .replace("2학기 중간시험", "2nd Semester Midterm Exam")
                .replace("종합작품전(30주) 정상수업", "30th Comprehensive Art Exhibition — Regular Classes")
                .replace("2학기 보강기간", "2nd Semester Makeup Class Period")

                // 上一轮已补充词条
                .replace("2026학년도 입학식(50회)", "50th Entrance Ceremony of 2026 Academic Year")
                .replace("수강신청 확인 및 수강정정 기간", "Course registration confirmation and adjustment period")
                .replace("수업일수 1/4선", "1/4 of total class days completed")
                .replace("수업일수 3/4선", "3/4 of total class days completed")
                .replace("1학기 중간시험", "1st Semester Midterm Exam")
                .replace("백호체육대회", "Baekho Sports Festival")
                .replace("개교기념일(49주년)", "49th School Founding Anniversary")
                .replace("부처님오신날", "Buddha's Birthday")
                .replace("대체휴일(부처님오신날)", "Substitute Holiday for Buddha's Birthday")
                .replace("1학기 개강", "1st Semester Begins")

                // 原有通用翻译
                .replace("신정", "New Year's Day")
                .replace("설날연휴", "Lunar New Year Holiday")
                .replace("삼일절", "Samiljeol")
                .replace("어린이날", "Children's Day")
                .replace("근로자의 날", "Labor Day")
                .replace("현충일", "Hyeonchungil")
                .replace("광복절", "Liberation Day")
                .replace("개천절", "Gaecheonjeol")
                .replace("한글날", "Hangul Day")
                .replace("성탄절", "Christmas")
                .replace("대체휴일", "Substitute Holiday")
                .replace("개강", "Semester Start")
                .replace("하계방학", "Summer Vacation")
                .replace("동계방학", "Winter Vacation")
                .replace("수강신청", "Course Registration")
                .replace("수강정정", "Course Adjustment")
                .replace("보강기간", "Makeup Class Period")
                .replace("계절수업", "Seasonal Course")
                .replace("수업일수", "Class Days")
                .replace("중간시험", "Midterm Exam")
                .replace("기말시험", "Final Exam")
                .replace("신입생 등록 기간", "New Student Registration Period")
                .replace("재학생 등록", "Current Student Registration")
                .replace("휴학신청 기간", "Leave of Absence Application Period")
                .replace("복학신청", "Return to School Application")
                .replace("입학식", "Entrance Ceremony")
                .replace("학위수여식", "Graduation Ceremony")
                .replace("체육대회", "Sports Festival")
                .replace("교직원세미나", "Faculty Seminar")
                .replace("추모일", "Memorial Day")
                .replace("개교기념일", "School Founding Anniversary")
                .replace("제9회 지방선거", "9th Local Election")
                .replace("졸업", "Graduation")
                .replace("종합작품전", "Comprehensive Art Exhibition")
                .replace("선택 확인 및 조정 기간", "Course Confirmation and Adjustment Period")
                .replace("선택 신청 기간", "Course Application Period")
                .replace("백호", "Baekho")
                .replace("학교기념일", "School Anniversary")
                .replace("제1학기", "1st Semester")
                .replace("제2학기", "2nd Semester")
                .replace("선택 기간", "Course Period")
                .replace("등록/복학신청", "Registration / Return Application")
                .replace("학사일정", "School Calendar")
                .replace("학년도", "Academic Year")
                .replace("회", "Session")
                .replace("제", "No.")
                .replace("전", "Pre")
                .replace("후", "Post")
                .replace("중간", "Midterm")
                .replace("기말", "Final")
                .replace("보충", "Supplement")
                .replace("확인", "Confirmation")
                .replace("기간", "Period")
                .replace("일", "Day")
                .replace("개학", "Semester Start")
                .replace("방학", "Vacation")
                .replace("기", "Semester")
                .replace("수강", "Course")
                .replace("등록", "Registration")
                .replace("휴학", "Leave of Absence")
                .replace("복학", "Return to School")
                .replace("졸업식", "Graduation Ceremony")
                .replace("입학", "Entrance")
                .replace("학위수여", "Graduation")
                .replace("체육", "Sports")
                .replace("대회", "Festival")
                .replace("교직원", "Faculty")
                .replace("세미나", "Seminar")
                .replace("추모", "Memorial")
                .replace("개교", "School Founding")
                .replace("지방선거", "Local Election")
                .replace("선거", "Election")
                .replace("작품전", "Art Exhibition")
                .replace("1/4선", "1/4 Progress")
                .replace("2/4선", "2/4 Progress")
                .replace("3/4선", "3/4 Progress")
                .replace("4/4선", "4/4 Progress")
                .replace("선", "Progress")
                .replace("하계", "Summer")
                .replace("동계", "Winter")
                .replace("보강", "Makeup Class")
                .replace("수강신청확인및수강정정기간", "Course Registration Confirmation and Adjustment Period")
                .replace("수업일수2/4선", "Class Days 2/4 Progress")
                .replace("수업일수4/4선", "Class Days 4/4 Progress")
                .replace("2학기개강", "2nd Semester Begins")
                .replace("2학기기말시험", "2nd Semester Final Exam")
                .replace("추석연휴", "Chuseok Holiday");
    }

    // 越南语（完全对应上面顺序）
    private String translateToVietnamese(String s) {
        return s
                // 本次新增词条（优先长句）
                .replace("1학기 보강기간", "Kỳ học bồi dưỡng học kỳ 1")
                .replace("1학기 기말시험", "Kỳ thi cuối kỳ học kỳ 1")
                .replace("2학기 기말시험", "Kỳ thi cuối kỳ học kỳ 2")
                .replace("2학기 개강", "Bắt đầu học kỳ 2")
                .replace("영진교육재단 설립자 송헌 최달근 박사 추모일", "Ngày tưởng niệm Tiến sĩ Song Heon và Tiến sĩ Choi Dal-geun, người sáng lập Quỹ Giáo dục Youngjin")
                .replace("2학기 중간시험", "Kỳ thi giữa kỳ học kỳ 2")
                .replace("종합작품전(30주) 정상수업", "Triển lãm tác phẩm tổng hợp (lần thứ 30) — Học bình thường")
                .replace("2학기 보강기간", "Kỳ học bồi dưỡng học kỳ 2")

                // 上一轮已补充词条
                .replace("2026학년도 입학식(50회)", "Lễ nhập học lần thứ 50 năm học 2026")
                .replace("수강신청 확인 및 수강정정 기간", "Kỳ xác nhận và điều chỉnh đăng ký môn học")
                .replace("수업일수 1/4선", "Hoàn thành 1/4 số ngày học")
                .replace("수업일수 3/4선", "Hoàn thành 3/4 số ngày học")
                .replace("1학기 중간시험", "Kỳ thi giữa kỳ học kỳ 1")
                .replace("백호체육대회", "Hội thể thao Bạch Hổ")
                .replace("개교기념일(49주년)", "Ngày kỷ niệm thành lập trường (49 năm)")
                .replace("부처님오신날", "Ngày Phật Đản")
                .replace("대체휴일(부처님오신날)", "Ngày nghỉ thay thế cho Ngày Phật Đản")
                .replace("1학기 개강", "Bắt đầu học kỳ 1")

                // 原有通用翻译
                .replace("신정", "Tết Dương lịch")
                .replace("설날연휴", "Tết Nguyên Đán")
                .replace("삼일절", "Ngày Samiljeol")
                .replace("어린이날", "Ngày Thiếu nhi")
                .replace("근로자의 날", "Ngày Quốc tế Lao động")
                .replace("현충일", "Ngày Hyeonchungil")
                .replace("광복절", "Ngày Giải phóng")
                .replace("개천절", "Ngày Gaecheonjeol")
                .replace("한글날", "Ngày chữ Hangeul")
                .replace("성탄절", "Giáng sinh")
                .replace("대체휴일", "Ngày nghỉ thay thế")
                .replace("개강", "Bắt đầu học kỳ")
                .replace("하계방학", "Kỳ nghỉ hè")
                .replace("동계방학", "Kỳ nghỉ đông")
                .replace("수강신청", "Đăng ký môn học")
                .replace("수강정정", "Điều chỉnh môn học")
                .replace("보강기간", "Kỳ học bồi dưỡng")
                .replace("계절수업", "Môn học theo mùa")
                .replace("수업일수", "Số ngày học")
                .replace("중간시험", "Kỳ thi giữa kỳ")
                .replace("기말시험", "Kỳ thi cuối kỳ")
                .replace("신입생 등록 기간", "Kỳ đăng ký sinh viên mới")
                .replace("재학생 등록", "Kỳ đăng ký sinh viên đang học")
                .replace("휴학신청 기간", "Kỳ đăng ký nghỉ học")
                .replace("복학신청", "Kỳ đăng ký trở lại học")
                .replace("입학식", "Lễ nhập học")
                .replace("학위수여식", "Lễ trao bằng")
                .replace("체육대회", "Hội thể thao")
                .replace("교직원세미나", "Hội thảo cán bộ giáo dục")
                .replace("추모일", "Ngày tưởng niệm")
                .replace("개교기념일", "Ngày thành lập trường")
                .replace("제9회 지방선거", "Cuộc bầu cử địa phương lần thứ 9")
                .replace("졸업", "Tốt nghiệp")
                .replace("종합작품전", "Triển lãm tác phẩm tổng hợp")
                .replace("선택 확인 및 조정 기간", "Kỳ xác nhận và điều chỉnh môn học")
                .replace("선택 신청 기간", "Kỳ đăng ký môn học")
                .replace("백호", "Bạch Hổ")
                .replace("학교기념일", "Ngày kỷ niệm trường")
                .replace("제1학기", "Học kỳ 1")
                .replace("제2학기", "Học kỳ 2")
                .replace("선택 기간", "Kỳ môn học")
                .replace("등록/복학신청", "Đăng ký / Đăng ký trở lại học")
                .replace("학사일정", "Lịch học")
                .replace("학년도", "Năm học")
                .replace("회", "Lần")
                .replace("제", "Lần thứ")
                .replace("전", "Trước")
                .replace("후", "Sau")
                .replace("중간", "Giữa kỳ")
                .replace("기말", "Cuối kỳ")
                .replace("보충", "Bổ sung")
                .replace("확인", "Xác nhận")
                .replace("기간", "Kỳ")
                .replace("일", "Ngày")
                .replace("개학", "Bắt đầu học kỳ")
                .replace("방학", "Kỳ nghỉ")
                .replace("기", "Học kỳ")
                .replace("수강", "Môn học")
                .replace("등록", "Đăng ký")
                .replace("휴학", "Nghỉ học")
                .replace("복학", "Trở lại học")
                .replace("졸업식", "Lễ tốt nghiệp")
                .replace("입학", "Nhập học")
                .replace("학위수여", "Trao bằng")
                .replace("체육", "Thể thao")
                .replace("대회", "Hội")
                .replace("교직원", "Cán bộ giáo dục")
                .replace("세미나", "Hội thảo")
                .replace("추모", "Tưởng niệm")
                .replace("개교", "Thành lập trường")
                .replace("지방선거", "Bầu cử địa phương")
                .replace("선거", "Bầu cử")
                .replace("작품전", "Triển lãm tác phẩm")
                .replace("1/4선", "Tiến độ 1/4")
                .replace("2/4선", "Tiến độ 2/4")
                .replace("3/4선", "Tiến độ 3/4")
                .replace("4/4선", "Tiến độ 4/4")
                .replace("선", "Tiến độ")
                .replace("하계", "Mùa hè")
                .replace("동계", "Mùa đông")
                .replace("보강", "Học bồi dưỡng")
                .replace("수강신청확인및수강정정기간", "Kỳ xác nhận và điều chỉnh đăng ký môn học")
                .replace("수업일수2/4선", "Số ngày học tiến độ 2/4")
                .replace("수업일수4/4선", "Số ngày học tiến độ 4/4")
                .replace("2학기개강", "Bắt đầu học kỳ 2")
                .replace("2학기기말시험", "Kỳ thi cuối kỳ học kỳ 2")
                .replace("추석연휴", "Tết Trung Thu");
    }
}